"""empty message

Revision ID: 12188221d150
Revises: 20163022110d
Create Date: 2015-04-11 00:27:54.019000

"""

# revision identifiers, used by Alembic.
revision = '12188221d150'
down_revision = '20163022110d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
