"""empty message

Revision ID: 153b61318af6
Revises: 413b4d34fe8d
Create Date: 2015-04-11 16:01:02.614000

"""

# revision identifiers, used by Alembic.
revision = '153b61318af6'
down_revision = '413b4d34fe8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
