"""empty message

Revision ID: 20163022110d
Revises: 2ca87d810f99
Create Date: 2015-04-11 00:26:54.258000

"""

# revision identifiers, used by Alembic.
revision = '20163022110d'
down_revision = '2ca87d810f99'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('corp_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'corporation', ['corp_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'corp_id')
    ### end Alembic commands ###
