"""empty message

Revision ID: 21ca2aa72535
Revises: 4bb267bf977a
Create Date: 2015-04-12 13:12:02.124000

"""

# revision identifiers, used by Alembic.
revision = '21ca2aa72535'
down_revision = '4bb267bf977a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
