"""empty message

Revision ID: 2ca87d810f99
Revises: 2ce88a56334
Create Date: 2015-04-11 00:26:23.096000

"""

# revision identifiers, used by Alembic.
revision = '2ca87d810f99'
down_revision = '2ce88a56334'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alliance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('ticker', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corporation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('ticker', sa.String(length=32), nullable=True),
    sa.Column('alliance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corporation')
    op.drop_table('alliance')
    ### end Alembic commands ###
