"""empty message

Revision ID: 2e1382ecc795
Revises: 21ca2aa72535
Create Date: 2015-04-12 13:34:58.152000

"""

# revision identifiers, used by Alembic.
revision = '2e1382ecc795'
down_revision = '21ca2aa72535'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_address', sa.String(length=128), nullable=True),
    sa.Column('slack_user_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_member')
    ### end Alembic commands ###
