"""empty message

Revision ID: 3b0797efd5c8
Revises: 12188221d150
Create Date: 2015-04-11 15:57:04.855000

"""

# revision identifiers, used by Alembic.
revision = '3b0797efd5c8'
down_revision = '12188221d150'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('subdomain', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    ### end Alembic commands ###
