"""empty message

Revision ID: 413b4d34fe8d
Revises: 3b0797efd5c8
Create Date: 2015-04-11 15:59:25.268000

"""

# revision identifiers, used by Alembic.
revision = '413b4d34fe8d'
down_revision = '3b0797efd5c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('alliance_id', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('corp_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'team', 'alliance', ['alliance_id'], ['id'])
    op.create_foreign_key(None, 'team', 'corporation', ['corp_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_column('team', 'corp_id')
    op.drop_column('team', 'alliance_id')
    ### end Alembic commands ###
